In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

In [2]:
from src.data_loader import load_dataset

df1 = load_dataset("../Data/Raw_data/nifty500_complete_daily_data.csv")
df2 = load_dataset("../Data/Raw_data/nifty500_5yr_data.csv")

In [3]:
df1.head()

        Date  Ticker        Open        High         Low       Close    Volume
0 2021-06-24  360ONE  286.512512  286.787506  283.000000  285.687500   83460.0
1 2021-06-25  360ONE  286.750000  287.012512  277.750000  281.437500   80536.0
2 2021-06-28  360ONE  286.000000  286.000000  278.200012  281.049988   52828.0
3 2021-06-29  360ONE  282.500000  285.287506  280.137512  282.424988  135796.0
4 2021-06-30  360ONE  282.000000  296.250000  280.587494  291.087494  219880.0

In [4]:
df2.head()

,Date,Ticker,Open,High,Low,Close,Volume,Notes
0,2021-06-09,360ONE,260.813755,262.150806,249.887157,251.816010,59152.0,NaN
1,2021-06-10,360ONE,253.997012,260.046642,251.848943,257.131409,41084.0,NaN
2,2021-06-11,360ONE,259.443804,263.246739,256.714877,260.758942,232800.0,NaN
3,2021-06-14,360ONE,261.931602,263.027550,258.939658,259.619141,74364.0,NaN
4,2021-06-15,360ONE,260.791773,260.791773,252.144728,253.821533,149636.0,NaN

In [5]:
print(df1.shape)
print(df2.shape)

(619236, 7)
(551643, 8)

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 619236 entries, 0 to 619235
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Date    619236 non-null  datetime64[ns]
 1   Ticker  619236 non-null  object
 2   Open    553957 non-null  float64
 3   High    553957 non-null  float64
 4   Low     553957 non-null  float64
 5   Close   553957 non-null  float64
 6   Volume  553957 non-null  float64
dtypes: datetime64[ns](1), float64(5), object(1)
memory usage: 33.1+ MB

In [7]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 551643 entries, 0 to 551642
Data columns (total 8 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Date    551643 non-null  datetime64[ns]
 1   Ticker  551643 non-null  object
 2   Open    551643 non-null  float64
 3   High    551643 non-null  float64
 4   Low     551643 non-null  float64
 5   Close   551643 non-null  float64
 6   Volume  551643 non-null  float64
 7   Notes   465 non-null     object
dtypes: datetime64[ns](1), float64(5), object(2)
memory usage: 33.7+ MB

In [8]:
df1.describe()

,Date,Open,High,Low,Close,Volume
count,619236,553957.000000,553957.000000,553957.000000,553957.000000,5.539570e+05
mean,2023-12-22 09:58:50.097087744,1919.365653,1945.299781,1891.148463,1916.977624,5.888574e+06
min,2021-06-24 00:00:00,3.500000,3.650000,3.350000,3.500000,0.000000e+00
25%,2022-09-20 18:00:00,258.670013,263.299988,253.759995,258.299988,2.451250e+05
50%,2023-12-20 12:00:00,642.950012,653.450012,632.000000,641.900024,8.359810e+05
75%,2025-03-21 18:00:00,1500.000000,1521.699951,1476.199951,1498.966675,3.241047e+06
max,2026-06-22 00:00:00,161980.000000,163600.000000,160285.000000,162295.000000,1.807991e+09
std,NaN,6672.647238,6741.486154,6593.127894,6662.826456,2.783033e+07

In [9]:
df2.describe()

,Date,Open,High,Low,Close,Volume
count,551643,551643.000000,551643.000000,551643.000000,551643.000000,5.516430e+05
mean,2024-01-09 18:07:57.661096448,1882.927583,1908.446096,1855.072520,1880.521817,5.929137e+06
min,2021-06-09 00:00:00,3.500000,3.650000,3.350000,3.500000,2.370000e+02
25%,2022-10-12 00:00:00,246.780998,251.451467,242.128479,246.402252,2.484385e+05
50%,2024-01-25 00:00:00,631.138124,641.790427,620.500000,630.408203,8.441400e+05
75%,2025-04-21 00:00:00,1470.415559,1492.066060,1447.570744,1468.885010,3.261656e+06
max,2026-06-09 00:00:00,161973.590589,163593.537167,160278.657659,162288.578125,1.807991e+09
std,NaN,6610.161851,6678.209196,6531.022663,6600.118226,2.790023e+07

In [10]:
df1.isnull().sum()

Date          0
Ticker        0
Open      65279
High      65279
Low       65279
Close     65279
Volume    65279
dtype: int64

In [11]:
df2.isnull().sum()

Date           0
Ticker         0
Open           0
High           0
Low            0
Close          0
Volume         0
Notes     551178
dtype: int64

In [12]:
print(df1.duplicated().sum())
print(df2.duplicated().sum())

0
0

In [13]:
print(df1["Ticker"].nunique())
print(df2["Ticker"].nunique())

501
500

In [14]:
print(df1["Date"].min())
print(df1["Date"].max())

print(df2["Date"].min())
print(df2["Date"].max())

2021-06-24 00:00:00
2026-06-22 00:00:00
2021-06-09 00:00:00
2026-06-09 00:00:00

In [15]:
print(df1.columns.tolist())
print(df2.columns.tolist())

['Date', 'Ticker', 'Open', 'High', 'Low', 'Close', 'Volume']
['Date', 'Ticker', 'Open', 'High', 'Low', 'Close', 'Volume', 'Notes']

In [25]:
from src.cleaning import clean_data

clean_df = clean_data(df2)
clean_df.head()

clean_df.to_csv("../Data/Processed_data/cleaned_nifty500.csv", index=False)